### PR TITLE
Removing dash so the link works

### PR DESCRIPTION
**Pull request by DecimalTurn**

### CODE REVIEW

**Comment by linegel** [comment]
@all-contributors please add @DecimalTurn for doc

**Comment by linegel** [comment]
@all-contributors please add @DecimalTurn for doc

**Comment by linegel** [comment]
@DecimalTurn looks like this dash are required by @all-contributors

**Comment by linegel** [comment]
@DecimalTurn and allcontributors bot wanna put it back when adding you to contributors list here https://github.com/linegel/forked-meme/pull/12/files so there even merge conflict with README.md (you changes from this PR)

**Comment by DecimalTurn** [comment]
Weird, I thought the idea was to have a link to the Contributors section, but if allcontributors needs that dash to work properly, feel free to change it back.

**Comment by linegel** [comment]
> Weird, I thought the idea was to have a link to the Contributors section, but if allcontributors needs that dash to work properly, feel free to change it back.

Resolved conflict in favor of not having the dash. That behavior is very weird actually

**Pull request merged**
